### PR TITLE
Improved readme

### PR DESCRIPTION
**Pull request by aniketpant**
This is probably the worst way of starting out in a project but I happened to come across it. While I was trying to install, I faced some bumps here and there. So, I added the changes you see on the files for newcomers. They are very small but I hope merging them won't be an issue.

Along with I couldn't help notice that `node_modules` is included in the project directory and not added in `.gitignore`. The folder is not needed because users can install dependencies themselves as they are provided in `package.json`.

The actual process for the installation should be -
1. installation of `node.js`, `nvm`, `npm`, `coffee-script`
2. all dependencies should go in `package.json` # that is the purpose of the file
3. `npm install`

Notes:
- `nvm` is needed because v0.6.10 is needed for running simplecv-js
- Ideally all files under `node_modules` should be deleted as they increase the size of the repository and these files are supposed to installed by the user when he sets up the repository. Maybe, to improve the process, a shell script can be provided.

### CODE REVIEW

**Comment by chaithuzz2** [comment]
hi aniket , 
                 i've been trying to set this up since two days. all iam getting is trouble. i've been able to overcome the above issue . but after installing node , npm , brunch , when i go into the git cloned folder of simplecv-js  and run "brunch build" . i'm getting an error. i've been stuck with this from 16 hrs and i am tired.iam showing you the error log below. 

module.js:340
    throw err;
          ^
Error: Cannot find module '/root/local/lib/node_modules/brunch/lib/cli'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/local/lib/node_modules/brunch/bin/brunch:7:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

can you please help me with this. i'd really appreciate it if you give me a  step by step procedure. thanks in advance

**Comment by aniketpant** [comment]
@chaithuzz2 There are some basic requirement for running simplecv-js.

First of all you need nodejs installed `~v0.6.10`. The version has to be `0.6.10`. The easiest way to install nodejs is via nvm (node version manager).

Second, you will need to install `coffee-script` and `brunch` via `npm` (node packet manager).

Third, run `npm install` when you are in the repository. This will install all missing dependencies.

Once all of this is done, you can get to the installation of `coffee-script-brunch` via `npm` and then try running the commands - `brunch build` and `brunch watch`.

**Comment by xamox** [comment]
This has merge conflicts can you please correct?

**Comment by aniketpant** [comment]
Had to a forced push for some reason. Can you confirm if it merges fine now?
And I checked that there was conflict because `README.md` was changed.

**Pull request merged**
